export const CAMPAIGN_MANAGEMENT = {
  GET_TREE_FOLDER: 'campaign-management/GET_TREE_FOLDER',
  CREATE_TREE_FOLDER: 'campaign-management/CREATE_TREE_FOLDER',
  GET_CAMPAIGN_IN_FOLDER: 'campaign-management/GET_CAMPAIGN_IN_FOLDER',
  EDIT_TREE_FOLDER: 'campaign-management/EDIT_TREE_FOLDER',
  DELETE_TREE_FOLDER: 'campaign-management/DELETE_TREE_FOLDER',
  MOVE_TREE_FOLDER: 'campaign-management/MOVE_TREE_FOLDER',
  COUNT_CAMPAIGN: 'campaign-management/COUNT_CAMPAIGN',
  GET_LIST_CAMPAIGN_AUTO: 'campaign-management/GET_LIST_CAMPAIGN_AUTO',
  SAVE_CAMPAIGN_AUTO: 'campaign-management/SAVE_CAMPAIGN_AUTO',
  GET_NODE: 'campaign-management/GET_NODE',
  GET_INFO_CAMPAIGN: 'campaign-management/GET_INFO_CAMPAIGN',
  GET_DIAGRAM_CAMPAIGN: 'campaign-management/GET_DIAGRAM_CAMPAIGN',
  VALIDATE_DIAGRAM_CAMPAIGN: 'campaign-management/VALIDATE_DIAGRAM_CAMPAIGN',
  GET_EMAIL_TEST: 'campaign-management/GET_EMAIL_TEST',
  TEST_CAMPAIGN: 'campaign-management/TEST_CAMPAIGN',
  SAVE_CAMPAIGN_AUTO_VERSION: 'campaign-management/SAVE_CAMPAIGN_AUTO_VERSION',
  GET_LIST_VERSION: 'campaign-management/GET_LIST_VERSION',
  DELETE_VERSION: 'campaign-management/DELETE_VERSION',
  STOP_VERSION: 'campaign-management/STOP_VERSION',
  CLONE_VERSION: 'campaign-management/CLONE_VERSION',
  LIST_CUSTOMER_VERSION_PROCESS: 'campaign-management/LIST_CUSTOMER_VERSION_PROCESS',
  VIEW_INTERACTIVE: 'campaign-management/VIEW_INTERACTIVE',
  RESET_DATA_CAMPAIGN: 'campaign-management/RESET_DATA_CAMPAIGN',
  ACTIVE_PROCESS_CAMPAIGN: 'campaign-management/ACTIVE_PROCESS_CAMPAIGN',
  GET_TEMPLATE_CAMPAIGN: 'campaign-management/GET_TEMPLATE_CAMPAIGN',
  CLONE_VERSION_BY_ID: 'campaign-management/CLONE_VERSION_BY_ID',
  VALIDATE_GRAPH: 'campaign-management/VALIDATE_GRAPH',
  RESET_VERSION : 'campaign-management/RESET_VERSION',
  COPY_CJID_CAMPAIGN :'campaign-management/COPY_CJID_CAMPAIGN'
};
