export const CAMPAIGN_MANAGAMENT = {
  GET_TREE_FOLDER: 'campaign-managament/GET_TREE_FOLDER',
  CREATE_TREE_FOLDER: 'campaign-managament/CREATE_TREE_FOLDER',
  GET_CAMPAIGN_IN_FOLDER: 'campaign-managament/GET_CAMPAIGN_IN_FOLDER',
  EDIT_TREE_FOLDER: 'campaign-managament/EDIT_TREE_FOLDER',
  DELETE_TREE_FOLDER: 'campaign-managament/DELETE_TREE_FOLDER',
  MOVE_TREE_FOLDER: 'campaign-managament/MOVE_TREE_FOLDER',
  COUNT_CAMPAIGN: 'campaign-managament/COUNT_CAMPAIGN',
  GET_LIST_CAMPAIGN_AUTO: 'campaign-managament/GET_LIST_CAMPAIGN_AUTO',
  SAVE_CAMPAIGN_AUTO: 'campaign-managament/SAVE_CAMPAIGN_AUTO',
  GET_NODE: 'campaign-managament/GET_NODE',
  GET_INFO_CAMPAIGN: 'campaign-managament/GET_INFO_CAMPAIGN',
  GET_DIAGRAM_CAMPAIGN: 'campaign-managament/GET_DIAGRAM_CAMPAIGN',
  VALIDATE_DIAGRAM_CAMPAIGN: 'campaign-managament/VALIDATE_DIAGRAM_CAMPAIGN',
  GET_EMAIL_TEST: 'campaign-managament/GET_EMAIL_TEST',
  TEST_CAMPAIGN: 'campaign-managament/TEST_CAMPAIGN',
  SAVE_CAMPAIGN_AUTO_VERSION: 'campaign-managament/SAVE_CAMPAIGN_AUTO_VERSION',
  GET_LIST_VERSION: 'campaign-managament/GET_LIST_VERSION',
  DELETE_VERSION: 'campaign-managament/DELETE_VERSION',
  STOP_VERSION: 'campaign-managament/STOP_VERSION',
  CLONE_VERSION: 'campaign-managament/CLONE_VERSION',
  LIST_CUSTOMER_VERSION_PROCESS: 'campaign-managament/LIST_CUSTOMER_VERSION_PROCESS',
  VIEW_INTERACTIVE: 'campaign-managament/VIEW_INTERACTIVE',
  RESET_DATA_CAMPAIGN: 'campaign-managament/RESET_DATA_CAMPAIGN',
  ACTIVE_PROCESS_CAMPAIGN: 'campaign-managament/ACTIVE_PROCESS_CAMPAIGN',
  GET_TEMPLATE_CAMPAIGN: 'campaign-managament/GET_TEMPLATE_CAMPAIGN'
};
