export const CUSTOMER_GROUP_ATTRIBUTE = {
  GET_LIST_CUSTOMER_GROUP: 'group-atrribute-customer/GET_LIST_CUSTOMER_GROUP',
  POST_INSERT_CUSTOMER_GROUP: 'group-atrribute-customer/POST_INSERT_CUSTOMER_GROUP',
  POST_UPDATE_CUSTOMER_GROUP: 'group-atrribute-customer/POST_UPDATE_CUSTOMER_GROUP',
  POST_MERGE_CUSTOMER_GROUP: 'group-atrribute-customer/POST_MERGE_CUSTOMER_GROUP',
  POST_DELETE_CUSTOMER_GROUP: 'group-atrribute-customer/POST_DELETE_CUSTOMER_GROUP',
  GET_LIST_FIELD_DATA: 'group-atrribute-customer/GET_LIST_FIELD_DATA'
};

export const INSERT_CUSTOMER_GROUP = 'INSERT_CUSTOMER_GROUP';
export const DELETE_CUSTOMER_GROUP = 'DELETE_CUSTOMER_GROUP';
export const MERGE_CUSTOMER_GROUP = 'MERGE_CUSTOMER_GROUP';
export const EDIT_CUSTOMER_GROUP = 'EDIT_CUSTOMER_GROUP';
