export const CUSTOMER_GROUP_ATTRIBUTE = {
  GET_LIST_CUSTOMER_GROUP: 'group-atrribute-customer/GET_LIST_CUSTOMER_GROUP',
  POST_INSERT_CUSTOMER_GROUP: 'group-atrribute-customer/POST_INSERT_CUSTOMER_GROUP',
  POST_UPDATE_CUSTOMER_GROUP: 'group-atrribute-customer/POST_UPDATE_CUSTOMER_GROUP',
  GET_FIND_CUSTOMER_WITH_CONDITION: 'group-atrribute-customer/GET_FIND_CUSTOMER_WITH_CONDITION',
  POST_DELETE_CUSTOMER_GROUP: 'group-atrribute-customer/POST_DELETE_CUSTOMER_GROUP',
  GET_LIST_FIELD_DATA: 'group-atrribute-customer/GET_LIST_FIELD_DATA',
  GET_LIST_CUSTOMER_WITH_GROUP_ID: 'group-atrribute-customer/GET_LIST_CUSTOMER_WITH_GROUP_ID',
  GET_SINGLE_CUSTOMER_GROUP_FIELD: 'group-atrribute-customer/GET_SINGLE_CUSTOMER_GROUP_FIELD'
};

export const INSERT_CUSTOMER_GROUP = 'INSERT_CUSTOMER_GROUP';
export const DELETE_CUSTOMER_GROUP = 'DELETE_CUSTOMER_GROUP';
export const MERGE_CUSTOMER_GROUP = 'MERGE_CUSTOMER_GROUP';
export const EDIT_CUSTOMER_GROUP = 'EDIT_CUSTOMER_GROUP';
