export const NAVIGATION_INFO = {
  PUT_NAVIGATION_ID: 'navigationInfo/PUT_NAVIGATION_ID',
  PUT_NAVIGATION_NAME: 'navigationInfo/PUT_NAVIGATION_NAME',
  PUT_NAVIGATION_FROMDATE: 'navigationInfo/PUT_NAVIGATION_FROMDATE',
  PUT_NAVIGATION_TODATE: 'navigationInfo/PUT_NAVIGATION_TODATE',
  PUT_NAVIGATION_DESCRIPTION: 'navigationInfo/PUT_NAVIGATION_DESCRIPTION',
  PUT_NAVIGATION_CUSTOMER_CAMPAIGNS: 'navigationInfo/PUT_NAVIGATION_CUSTOMER_CAMPAIGNS',
  PUT_NAVIGATION_REWARDS: 'navigationInfo/PUT_NAVIGATION_REWARDS',
  PUT_NAVIGATION_CONTENT_TEMPLATES: 'navigationInfo/PUT_NAVIGATION_CONTENT_TEMPLATES'
};
