export const PROPS_MANAGEMENT = {
  GET_LIST_PROPS: 'tagManagement/GET_LIST_PROPS',
  POST_INSERT_PROPS: 'tagManagement/POST_INSERT_PROPS',
  POST_UPDATE_PROPS: 'tagManagement/POST_UPDATE_PROPS',
  POST_MERGE_PROPS: 'tagManagement/POST_MERGE_PROPS',
  POST_DELETE_PROPS: 'tagManagement/POST_DELETE_PROPS'
};
