export const PROPS_MANAGEMENT = {
  GET_LIST_PROPS: 'tagManagement/GET_LIST_PROPS',
  POST_INSERT_PROPS: 'tagManagement/POST_INSERT_PROPS',
  POST_UPDATE_PROPS: 'tagManagement/POST_UPDATE_PROPS',
  POST_MERGE_PROPS: 'tagManagement/POST_MERGE_PROPS',
  POST_DELETE_PROPS: 'tagManagement/POST_DELETE_PROPS',
  RESET_PROPS: 'tagManagement/RESET_PROPS',
  OPEN_MODAL_PROPS: 'tagManagement/OPEN_MODAL_PROPS',
  OPEN_MODAL_EDIT_PROPS: 'tagManagement/OPEN_MODAL_EDIT_PROPS',
  GET_LIST_TEMP: 'tagManagement/GET_LIST_TEMP',
  GET_TEMP: 'tagManagement/GET_TEMP'
};
