export const USER_CAMPAIGN_ACTION_TYPES = {
  RESET_MESSAGE: 'userCampaign/RESET_MESSAGE',
  INFORMATION_CAMPAIGN: 'userCampaign/INFORMATION_CAMPAIGN',
  FETCH_CAMPAIGNS: 'userCampaign/FETCH_CAMPAIGNS',
  FETCH_CAMPAIGNS_ID: 'userCampaign/FETCH_CAMPAIGNS_ID',
  FETCH_CAMPAIGNS_STATUS: 'userCampaign/FETCH_CAMPAIGNS_STATUS',
  GET_STEP_CAMPAIGNS: 'userCampaign/GET_STEP_CAMPAIGNS',
  GET_CONTENT_PARAMS: 'userCampiatn/GET_CONTENT_PARAMS',
  GET_LIST_CUSTOMER_GROUP: 'userCampaign/GET_LIST_CUSTOMER_GROUP'
};
