export const USER_CAMPAIGN_ACTION_TYPES = {
  FETCH_ROLES: 'userCampaign/FETCH_ROLES',
  FETCH_USERS: 'userCampaign/FETCH_USERS',
  FETCH_USER: 'userCampaign/FETCH_USER',
  CREATE_USER: 'userCampaign/CREATE_USER',
  UPDATE_USER: 'userCampaign/UPDATE_USER',
  DELETE_USER: 'userCampaign/DELETE_USER',
  DOWNLOAD_FILE: 'userCampaign/DOWNLOAD_FILE',
  UPLOAD_FILE: 'userCampaign/UPLOAD_FILE',
  DOWNLOAD_FILERE_SULTS: 'userCampaign/UPLOAD_FILERE_SULTS',
  RESET: 'userCampaign/RESET',
  FETCH_USER_CATEGORIES: 'userCampaign/FETCH_CATEGORIES',
  FETCH_SEARCH_USER: 'userCampaign/FETCH_SEARCH_USER',
  UPDATE_USER_CATEGORY: 'userCampaign/UPDATE_USER_CATEGORY',
  RESET_MESSAGE: 'userCampaign/RESET_MESSAGE',
  INFORMATION_CAMPAIGN: 'userCampaign/INFORMATION_CAMPAIGN'
};

export const CAMPAIGN_MANAGE_ACTION_TYPE = {
  FETCH_CAMPAIGNS: 'campaignManagement/FETCH_CAMPAIGNS'
};
