export const USER_RESTORE_ACTION_TYPES = {
  GET_USERS_DELETED_LIST: 'userRestore/GET_USERS_DELETED_LIST',
  RESTORE_USERS_BY_IDS: 'userRestore/RESTORE_USERS_BY_IDS',
  RESTORE_ALL_USERS_WITH_FILTER: 'userRestore/RESTORE_ALL_USERS_WITH_FILTER'
};
